spring.datasource.url=jdbc:postgresql://localhost:5432/lab11db
spring.datasource.username=postgres
spring.datasource.password=09polkmn76yt
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true